CREATE DATABASE IF NOT EXISTS empresadb;

USE empresadb;

CREATE TABLE IF NOT EXISTS ACT_PROV(
    CIF_PROVEEDOR varchar(10),
    RAZ_PROVEEDOR varchar(180),
    NUM_FACTURA int(10) PRIMARY KEY,
    DES_FACTURA int(10),
    BAS_IMPONIBLE varchar(10),
    IVA_IMPORTE int(3),
    TOT_IMPORTE int(10),
    FEC_FACTURA varchar(10),
    FEC_VENCIMIENTO varchar(10)
);

CREATE TABLE IF NOT EXISTS PROV_COMP(
    CIF_PROVEEDOR varchar(10) PRIMARY KEY,
    RAZ_PROVEEDOR varchar(180),
    REG_NOTARIAL varchar(10),
    SEG_RESPONSABILIDAD varchar(10),
    SEG_IMPORTE varchar(10),
    FEC_HOMOLOGACIÓN varchar(10)
);

ALTER TABLE ACT_PROV
ADD FOREIGN KEY (CIF_PROVEEDOR) REFERENCES PROV_COMP(CIF_PROVEEDOR);
